### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by quinti123** [codeproject/CodeProject.AI-ObjectDetectionCoral#5]
is there a changelog for  latest 2.9.0?

**Comment by ChrisMaunder** [comment]
I'll add this to the docs:

## Version 2.9

- Updated to .NET 9
- Support for Ubuntu 24.10
- Improvements to CUDA support in Windows and Linux
- Further Windows arm64 fixes
- Further macOS arm64 fixes
- General dev environment setup fixes
- Fixes for Windows installer when wget is missing
